AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Agapanthus: CFN Template to configure Athena WorkGroup. 

Metadata:
  TemplateName: athena-stack.yaml
  TemplateType: Athena WorkGroup
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Agapanthus
  Modification History: 
    - 1.0.0  - Jul 10, 2024   -- Initial Version.

  Resources: 
    - Athena WorkGroup
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyArn
    #################################### S3 Bucket #################################################
    - Label:
        default: "S3 Configuration:"
      Parameters:
      - S3LandingZoneBucketBaseName
    #################################### Athena WorkGroup ##########################################
    - Label:
        default: "Athena Configuration:"
      Parameters:
      - AthenaWorkGroupBaseName
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref."
      GitHubURL:
        default: "GitHub URL."
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA:
        default: "GitHub SHA"
      GitHubRepository:
        default: "GitHub Repository."
      CiBuild:
        default: "Ci Build."
      ################################## KMS Key ###################################################
      KmsMasterKeyArn:
        default: "Kms Key arn."
      ################################## Athena WorkGroup ##########################################
      AthenaWorkGroupBaseName: 
        default: "Athena WorkGroup."
      ################################## S3 Bucket #################################################
      S3LandingZoneBucketBaseName:
        default: "S3 Bucket Base Name."

Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: agapanthus
    Description: "The project name that will be used as resource name prefixes and will be used to tag resources to track the project cost."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The deployment environment (dev/test/prod)."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub ref name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The GitHub workflow run number for the latest CI/CD pipeline."
    Type: Number
  GitHubSHA:
    Default: "27e994ee4b064c37170c9a702c44b676c3295e1f"
    Description: "The sha value of the last commit."
    Type: String
  GitHubRepository:
    Default: 0052-agapanthus-cft
    Description: "The GitHub repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### KMS Key ###################################################
  KmsMasterKeyArn:
    Default: "arn:aws:kms:us-east-1:637423502513:key/494509e4-3bc5-44b8-9c4d-12449900d395"
    Description: "The KMS key arn used to encrypt the resources."
    Type: String
    MinLength: "75"
    MaxLength: "75"
    AllowedPattern: "[a-z:/0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."
  ###################################### S3 Bucket #################################################
  S3LandingZoneBucketBaseName:
    Default: some-s3-bucket-name
    Description: "The S3 Bucket base name for the source data, the region will be added as suffix by the template."
    Type: String
    MinLength: "3"
    MaxLength: "40"
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ###################################### Athena WorkGroup ##########################################
  AthenaWorkGroupBaseName:
    Default: workgroup
    Description: "The Athena WorkGroup base name for the source data, the region will be added as suffix by the template."
    Type: String
    MinLength: "3"
    MaxLength: "40"
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
Resources:
  ###################################### Athena WorkGroup ##########################################
  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Description: !Sub "${ProjectName} work group"
      Name: !Sub "${ProjectName}-${AthenaWorkGroupBaseName}-${Environment}-${AWS::Region}${CiBuild}"
      RecursiveDeleteOption: true
      State: ENABLED
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: CiBuild
        Value: !Ref CiBuild
      WorkGroupConfiguration: 
        BytesScannedCutoffPerQuery: 200000000
        CustomerContentEncryptionConfiguration: 
          KmsKey: !Ref KmsMasterKeyArn
        EnforceWorkGroupConfiguration: true
        EngineVersion: 
            EffectiveEngineVersion: Auto
            SelectedEngineVersion: AUTO
        PublishCloudWatchMetricsEnabled: true
        RequesterPaysEnabled: false
        ResultConfiguration: 
          AclConfiguration: 
            S3AclOption: BUCKET_OWNER_FULL_CONTROL
          EncryptionConfiguration: 
            EncryptionOption: SSE_KMS
            KmsKey: !Ref KmsMasterKeyArn
          ExpectedBucketOwner: !Ref AWS::AccountId
          OutputLocation: !Sub "s3://${ProjectName}-${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}${CiBuild}/athena-output/"
Outputs:
  AthenaWorkGroupName:
    Description: Athena WorkGroup Name.
    Value: !Ref AthenaWorkGroup
  AthenaEngineVersion:
    Description: Athena Engine Version.
    Value: !GetAtt AthenaWorkGroup.WorkGroupConfiguration.EngineVersion.EffectiveEngineVersion
  AthenaIAMUserArn:
    Description: Athena IAM User Arn.
    Value: !GetAtt AthenaWorkGroup.WorkGroupConfiguration.EngineVersion.EffectiveEngineVersion
