AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Agapanthus: CFN Template To Create a Glue Crawler. 

Metadata:
  TemplateName: glue-crawler-stack.yaml
  TemplateType: Glue Crawler
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Agapanthus
  Modification History: 
    - 1.0.0  - Jun 27, 2023   -- Initial Version.
    
  Resources: 
    - Glue Crawler
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    #################################### Glue Crawler ##############################################
    - Label:
        default: "Glue Crawler Configuration:"
      Parameters:
      - GlueDatabaseBaseName
      - GlueCrawlerBaseName
      - GlueCrawlerRoleBaseName
      - GlueCrawlerDescription
      - GlueCrawlerTablePrefixName
      - GlueDataBucketName
      - GlueCSVDataFolder
      - GlueJSONDataFolder
      # - GlueEventNotificationDataFolder
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project name."
      Environment:
        default: "Environment name."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub ref."
      GitHubURL:
        default: "GitHub URL."
      GitHubWFRunNumber:
        default: "GitHub workflow run number."
      GitHubSHA:
        default: "GitHub SHA."
      GitHubRepository:
        default: "GitHub repository."
      CiBuild:
        default: "Ci build."
      ########### Glue Crawler ##############################################
      GlueDatabaseBaseName:
        default: "The Name Of The Glue Database."
      GlueCrawlerBaseName:
        default: "Glue Crawler base name."
      GlueCrawlerRoleBaseName:
        default: "Glue Crawler Role Name."
      GlueCrawlerDescription:
        default: "Glue Crawler Description."
      GlueCrawlerTablePrefixName:
        default: "Glue Table Prefix."
      GlueDataBucketName:
        default: "Glue Crawler S3 Bucket Name."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: agapanthus
    Description: "The project name that will be used as resource name prefixes and will be used to tag resources to track the project cost."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The deployment environment (dev/test/prod)."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub ref name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The GitHub workflow run number for the latest CI/CD pipeline."
    Type: Number
  GitHubSHA:
    Default: "27e994ee4b064c37170c9a702c44b676c3295e1f"
    Description: "The sha value of the last commit."
    Type: String
  GitHubRepository:
    Default: 0052-agapanthus-cft
    Description: "The GitHub repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### Glue Crawler ##############################################
  GlueDatabaseBaseName:
    Default: glue-database-name
    Description: "The Glue database base name.The region will be added as suffix by the template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  GlueCrawlerBaseName:
    Default: glue-crawler
    Description: "The Glue database crawler base name.The region will be added as suffix by the template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  GlueCrawlerRoleBaseName:
    Default: crawler-role
    Description: "The base name of the glue iam role."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: "The"
  GlueCrawlerDescription:
    Default: glue crawler description
    Type: String
    MinLength: 0
    MaxLength: 200
    AllowedPattern: "[a-zA-Z0-9-. _]*"
    ConstraintDescription: "The length should be between 30 and 200, must alphanumeric character, space, dot(.), dash(-) or underscore(_)."
  GlueCrawlerTablePrefixName:
    Default: glue-table-prefix
    Description: "Glue table prefix."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-zA-Z-_]*"
    ConstraintDescription: "The length should be between 5 and 30, must alphanumeric character, dash (-) or underscore(_)."
  GlueDataBucketName:
    Default: some-s3-bucket-name
    Description: "The S3 bucket base name. Environment and region will be added by the template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter." 
  GlueCSVDataFolder:
    Default: "input"
    Description: "The raw CSV data folder."
    Type: String
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z-_//]*"
    ConstraintDescription: "The length should be between 3 and 20 and should only contain alphanumeric character, dash(-), underscore (_) or slash (/)."
  GlueJSONDataFolder:
    Default: "input"
    Description: "The raw JSON data folder."
    Type: String
    MinLength: 3
    MaxLength: 20
    AllowedPattern: "[a-zA-Z-_//]*"
    ConstraintDescription: "The length should be between 3 and 20 and should only contain alphanumeric character, dash(-), underscore (_) or slash (/)."
Resources:
  ###################################### Glue Crawler ##############################################
  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub '${ProjectName}-${GlueCrawlerBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      Role: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${ProjectName}-${GlueCrawlerRoleBaseName}${CiBuild}" 
      #Classifiers: none, use the default classifier
      Description: !Ref GlueCrawlerDescription
      #Schedule: none, use default run-on-demand
      DatabaseName: !Sub '${ProjectName}-${GlueDatabaseBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      Targets:
        S3Targets:
          # S3 Data Sources Path
          - Path: !Sub "s3://${GlueDataBucketName}/${GlueCSVDataFolder}"
          - Path: !Sub "s3://${GlueDataBucketName}/${GlueJSONDataFolder}"
      TablePrefix: !Ref GlueCrawlerTablePrefixName
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"
      Tags:
        "ProjectName": !Ref ProjectName
        "Environment": !Ref Environment
        "GitHubRef": !Ref GitHubRef
        "GitHubURL": !Ref GitHubURL
        "GitHubWFRunNumber": !Ref GitHubWFRunNumber
        "GitHubSHA": !Ref GitHubSHA
        "GitHubRepository": !Ref GitHubRepository
        "CiBuild": !Ref CiBuild
Outputs:
  GlueCrawlerArn:
    Description: The Arn Of The Glue Crawler.
    Value: !Ref GlueCrawler

