AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Agapanthus: CFN Template To A Glue Database. 

Metadata:
  TemplateName: glue-database-stack.yaml
  TemplateType: Glue Database
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Agapanthus
  Modification History: 
    - 1.0.0  - Jun 27, 2024   -- Initial Version.

  Resources: 
    - Glue Database
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label:
        default: "Project Name and Environment:"
      Parameters:
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - CiBuild
    #################################### Glue Database #############################################
    - Label:
        default: "Glue Database Configuration:"
      Parameters:
      - GlueDatabaseBaseName
      - GlueDatabaseDescription
    ParameterLabels:
      ################################## Project Name and Environment ##############################
      ProjectName:
        default: "Project name."
      Environment:
        default: "Environment name."
      ################################## GitHub Attributes #########################################
      CiBuild:
        default: "Ci build."
      ################################## Glue Database #############################################
      GlueDatabaseBaseName:
        default: "Glue Database Name."
      GlueDatabaseDescription:
        default: "Glue Database Description."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: agapanthus
    Description: "The project name that will be used as resource name prefixes and will be used to tag resources to track the project cost."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The deployment environment (dev/test/prod)."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
  ###################################### GitHub Attributes #########################################
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### Glue Database #########################################
  GlueDatabaseBaseName:
    Default: glue-database-name
    Description: "The Glue database name.the region will be added as suffix by the template."
    Type: String
    MinLength: 3
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  GlueDatabaseDescription:
    Description: "The Glue Databased Description."
    Type: String
    MinLength: 0
    MaxLength: 200
    AllowedPattern: "[a-zA-Z0-9-. _]*"
    ConstraintDescription: "The length should be between 30 and 200, must alphanumeric character, space, dot dash or underscore."
Resources:
  ###################################### Glue Database #############################################
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      DatabaseInput:
        Name: !Sub "${ProjectName}-${GlueDatabaseBaseName}-${Environment}-${AWS::Region}${CiBuild}"
        Description: !Ref GlueDatabaseDescription
      CatalogId: !Ref AWS::AccountId
Outputs:
  GlueDatabaseId:
    Description: Glue database Id
    Value: !Ref GlueDatabase
